<template>
  <div class="w-full animate-fade-in-up">
    <div v-if="loading" class="w-full flex flex-col items-center gap-6 py-12">
      <div class="relative w-20 h-20">
          <div class="absolute inset-0 border-4 border-base-content/10 rounded-full"/>
          <div class="absolute inset-0 border-4 border-primary border-t-transparent rounded-full animate-spin"/>
          <div class="absolute inset-0 flex items-center justify-center">
              <Icon name="heroicons:sparkles" class="w-8 h-8 text-primary animate-pulse" />
          </div>
      </div>
      <p class="text-lg font-medium text-base-content/60 animate-pulse">Generating answer...</p>
    </div>

    <div v-else-if="result" class="grid gap-6">
      <div class="card bg-base-100 shadow-xl border border-base-content/5 overflow-hidden">
        <div class="h-2 w-full bg-gradient-to-r from-primary via-secondary to-primary bg-size-200 animate-gradient"/>
        <div class="card-body p-5 md:p-10">
          <div class="flex items-start gap-4 md:gap-6">
            <div class="flex-shrink-0">
              <div class="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center">
                <Icon name="heroicons:chat-bubble-bottom-center-text" class="!w-6 !h-6 !text-primary" />
              </div>
            </div>
            <div class="flex-1 min-w-0 space-y-4">
              <div class="flex items-baseline justify-between">
                <h3 class="font-bold text-xl">Answer</h3>
                <div class="badge badge-ghost gap-1">
                  <Icon name="heroicons:check-circle" class="w-3 h-3 text-success" />
                  Generated by AI
                </div>
              </div>
              <div
                  class="prose prose-lg max-w-none w-full min-w-0 break-words prose-headings:text-base-content prose-p:text-base-content/90 prose-strong:text-primary"
                  v-html="parsedAnswer"
              />
              <div v-if="!isTyping" class="flex justify-between items-center pt-2 border-t border-base-content/10">
                <button class="btn btn-ghost btn-sm gap-2 text-base-content/60 hover:text-base-content" @click="$emit('reset')">
                  <Icon name="heroicons:arrow-path" class="w-4 h-4" />
                  Ask another question
                </button>
                <button class="btn btn-sm btn-ghost rounded-full transition-all duration-200" :title="copied ? 'Copied!' : 'Copy'" @click="copyToClipboard">
                  <Icon :name="copied ? 'heroicons:check' : 'heroicons:clipboard'" class="w-4 h-4" :class="copied ? 'text-success' : ''" />
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div v-if="!isTyping && (citations?.length || citationsLoading)" class="mt-4 space-y-4">
          <h4 class="font-bold text-lg flex items-center gap-2">
              <Icon name="heroicons:document-text" class="w-5 h-5 text-primary" />
              Referenced Projects
          </h4>
          
          <div v-if="citationsLoading" class="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div v-for="i in 2" :key="i" class="card bg-base-100 shadow-xl h-64 animate-pulse">
                  <div class="h-48 bg-base-200"/>
                  <div class="card-body p-4 space-y-2">
                      <div class="h-4 bg-base-200 rounded w-3/4"/>
                      <div class="h-3 bg-base-200 rounded w-full"/>
                  </div>
              </div>
          </div>
          
          <div v-else class="grid grid-cols-1 md:grid-cols-2 gap-4 animate-fade-in-up" style="animation-delay: 200ms;">
              <ProjectListItem 
                  v-for="project in citations" 
                  :key="project.id" 
                  :project="project"
              />
          </div>
      </div>

    </div>
    
    <div v-if="error" class="alert alert-error shadow-lg rounded-2xl mt-6 animate-shake">
      <Icon name="heroicons:exclamation-circle" class="w-6 h-6" />
      <div class="flex-1">
          <h3 class="font-bold">Error</h3>
          <div class="text-xs">{{ error }}</div>
      </div>
      <button class="btn btn-sm btn-ghost" @click="$emit('dismiss-error')">Dismiss</button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, onUnmounted } from 'vue'
import { marked } from 'marked'
import ProjectListItem from '~/components/project/list/ProjectListItem.vue'
import type { Project } from '@api'

const props = defineProps<{
  loading: boolean
  result: string | null
  error: string | undefined | null
  citations: Project[]
  citationsLoading: boolean
}>()

const emit = defineEmits<{
  (e: 'reset' | 'dismiss-error'): void
}>()

const displayedAnswer = ref('')
const isTyping = ref(false)
const copied = ref(false)
let typeInterval: NodeJS.Timeout | null = null

const parsedAnswer = computed(() => {
    const text = displayedAnswer.value
    const textWithCursor = isTyping.value ? text + '<span class="inline-block w-2 h-4 bg-primary ml-1 animate-pulse" style="vertical-align: middle;"></span>' : text
    return marked.parse(textWithCursor)
})

watch(() => props.result, (newVal) => {
  if (newVal) {
    typeAnswer(newVal)
  } else {
    displayedAnswer.value = ''
    if (typeInterval) clearInterval(typeInterval)
  }
})

function typeAnswer(text: string) {
  isTyping.value = true
  displayedAnswer.value = ''
  let i = 0
  
  if (typeInterval) clearInterval(typeInterval)
  
  typeInterval = setInterval(() => {
    if (i < text.length) {
      displayedAnswer.value += text.charAt(i)
      i++
    } else {
      if (typeInterval) clearInterval(typeInterval)
      isTyping.value = false
    }
  }, 15)
}

function copyToClipboard() {
    if (props.result) {
        navigator.clipboard.writeText(props.result)
        copied.value = true
        setTimeout(() => { copied.value = false }, 2000)
    }
}

onUnmounted(() => {
  if (typeInterval) clearInterval(typeInterval)
})
</script>

<style scoped>
.bg-size-200 {
  background-size: 200% 200%;
}

@keyframes gradient {
  0% { background-position: 0% 50%; }
  50% { background-position: 100% 50%; }
  100% { background-position: 0% 50%; }
}

.animate-gradient {
  animation: gradient 3s ease infinite;
}

@keyframes fadeInUp {
  from { opacity: 0; transform: translateY(20px); }
  to { opacity: 1; transform: translateY(0); }
}

.animate-fade-in-up {
  animation: fadeInUp 0.6s ease-out forwards;
}

@keyframes shake {
  0%, 100% { transform: translateX(0); }
  25% { transform: translateX(-5px); }
  75% { transform: translateX(5px); }
}

.animate-shake {
  animation: shake 0.4s ease-in-out;
}
</style>
