// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteCompanyByIdData, DeleteCompanyByIdResponses, DeleteProjectByIdData, DeleteProjectByIdResponses, DeleteTagByIdData, DeleteTagByIdResponses, GetCompanyByIdData, GetCompanyByIdResponses, GetCompanyBySlugData, GetCompanyBySlugResponses, GetCompanyData, GetCompanyResponses, GetMediaUploadsByFileNameData, GetMediaUploadsByFileNameResponses, GetProjectByIdData, GetProjectByIdRelatedData, GetProjectByIdRelatedResponses, GetProjectByIdResponses, GetProjectBySlugData, GetProjectBySlugResponses, GetProjectData, GetProjectResponses, GetTagByIdData, GetTagByIdResponses, GetTagBySlugData, GetTagBySlugResponses, GetTagData, GetTagResponses, PostCompanyData, PostCompanyResponses, PostProjectData, PostProjectResponses, PostTagData, PostTagResponses, PostVertexIngestData, PostVertexIngestResponses, PostVertexProjectsByIdDescriptionSuggestData, PostVertexProjectsByIdDescriptionSuggestResponses, PostVertexQueryData, PostVertexQueryResponses, PutCompanyByIdData, PutCompanyByIdResponses, PutProjectByIdData, PutProjectByIdResponses, PutProjectimageOptimiseData, PutProjectimageOptimiseResponses, PutTagByIdData, PutTagByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getCompany = <ThrowOnError extends boolean = false>(options?: Options<GetCompanyData, ThrowOnError>) => (options?.client ?? client).get<GetCompanyResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/company',
    ...options
});

export const postCompany = <ThrowOnError extends boolean = false>(options?: Options<PostCompanyData, ThrowOnError>) => (options?.client ?? client).post<PostCompanyResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    responseType: 'json',
    url: '/company',
    ...options,
    headers: {
        'Content-Type': null,
        ...options?.headers
    }
});

export const deleteCompanyById = <ThrowOnError extends boolean = false>(options: Options<DeleteCompanyByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteCompanyByIdResponses, unknown, ThrowOnError>({ url: '/company/{id}', ...options });

export const getCompanyById = <ThrowOnError extends boolean = false>(options: Options<GetCompanyByIdData, ThrowOnError>) => (options.client ?? client).get<GetCompanyByIdResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/company/{id}',
    ...options
});

export const putCompanyById = <ThrowOnError extends boolean = false>(options: Options<PutCompanyByIdData, ThrowOnError>) => (options.client ?? client).put<PutCompanyByIdResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    responseType: 'json',
    url: '/company/{id}',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

export const getCompanyBySlug = <ThrowOnError extends boolean = false>(options: Options<GetCompanyBySlugData, ThrowOnError>) => (options.client ?? client).get<GetCompanyBySlugResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/company/{slug}',
    ...options
});

export const getMediaUploadsByFileName = <ThrowOnError extends boolean = false>(options: Options<GetMediaUploadsByFileNameData, ThrowOnError>) => (options.client ?? client).get<GetMediaUploadsByFileNameResponses, unknown, ThrowOnError>({ url: '/media/uploads/{fileName}', ...options });

export const getProject = <ThrowOnError extends boolean = false>(options?: Options<GetProjectData, ThrowOnError>) => (options?.client ?? client).get<GetProjectResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/project',
    ...options
});

export const postProject = <ThrowOnError extends boolean = false>(options?: Options<PostProjectData, ThrowOnError>) => (options?.client ?? client).post<PostProjectResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    responseType: 'json',
    url: '/project',
    ...options,
    headers: {
        'Content-Type': null,
        ...options?.headers
    }
});

export const deleteProjectById = <ThrowOnError extends boolean = false>(options: Options<DeleteProjectByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteProjectByIdResponses, unknown, ThrowOnError>({ url: '/project/{id}', ...options });

export const getProjectById = <ThrowOnError extends boolean = false>(options: Options<GetProjectByIdData, ThrowOnError>) => (options.client ?? client).get<GetProjectByIdResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/project/{id}',
    ...options
});

export const putProjectById = <ThrowOnError extends boolean = false>(options: Options<PutProjectByIdData, ThrowOnError>) => (options.client ?? client).put<PutProjectByIdResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    responseType: 'json',
    url: '/project/{id}',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

export const getProjectBySlug = <ThrowOnError extends boolean = false>(options: Options<GetProjectBySlugData, ThrowOnError>) => (options.client ?? client).get<GetProjectBySlugResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/project/{slug}',
    ...options
});

export const getProjectByIdRelated = <ThrowOnError extends boolean = false>(options: Options<GetProjectByIdRelatedData, ThrowOnError>) => (options.client ?? client).get<GetProjectByIdRelatedResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/project/{id}/related',
    ...options
});

export const putProjectimageOptimise = <ThrowOnError extends boolean = false>(options?: Options<PutProjectimageOptimiseData, ThrowOnError>) => (options?.client ?? client).put<PutProjectimageOptimiseResponses, unknown, ThrowOnError>({ url: '/projectimage/optimise', ...options });

export const getTag = <ThrowOnError extends boolean = false>(options?: Options<GetTagData, ThrowOnError>) => (options?.client ?? client).get<GetTagResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/tag',
    ...options
});

export const postTag = <ThrowOnError extends boolean = false>(options?: Options<PostTagData, ThrowOnError>) => (options?.client ?? client).post<PostTagResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/tag',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const deleteTagById = <ThrowOnError extends boolean = false>(options: Options<DeleteTagByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteTagByIdResponses, unknown, ThrowOnError>({ url: '/tag/{id}', ...options });

export const getTagById = <ThrowOnError extends boolean = false>(options: Options<GetTagByIdData, ThrowOnError>) => (options.client ?? client).get<GetTagByIdResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/tag/{id}',
    ...options
});

export const putTagById = <ThrowOnError extends boolean = false>(options: Options<PutTagByIdData, ThrowOnError>) => (options.client ?? client).put<PutTagByIdResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/tag/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getTagBySlug = <ThrowOnError extends boolean = false>(options: Options<GetTagBySlugData, ThrowOnError>) => (options.client ?? client).get<GetTagBySlugResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/tag/{slug}',
    ...options
});

export const postVertexIngest = <ThrowOnError extends boolean = false>(options?: Options<PostVertexIngestData, ThrowOnError>) => (options?.client ?? client).post<PostVertexIngestResponses, unknown, ThrowOnError>({ url: '/vertex/ingest', ...options });

export const postVertexQuery = <ThrowOnError extends boolean = false>(options?: Options<PostVertexQueryData, ThrowOnError>) => (options?.client ?? client).post<PostVertexQueryResponses, unknown, ThrowOnError>({
    url: '/vertex/query',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const postVertexProjectsByIdDescriptionSuggest = <ThrowOnError extends boolean = false>(options: Options<PostVertexProjectsByIdDescriptionSuggestData, ThrowOnError>) => (options.client ?? client).post<PostVertexProjectsByIdDescriptionSuggestResponses, unknown, ThrowOnError>({
    url: '/vertex/projects/{id}/description/suggest',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
