// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:5105' | (string & {});
};

export type Company = {
    id: string;
    name: string;
    description: string;
    startDate?: string | null;
    endDate?: string | null;
    website?: string | null;
    logo?: string | null;
    slug: string;
};

export type CreateCompany = {
    name: string;
    description: string;
    startDate?: string | null;
    endDate?: string | null;
    logo?: Blob | File | null;
    website?: string | null;
};

export type CreateProject = {
    title: string;
    shortDescription: string;
    description: string;
    companyId?: string | null;
    startDate: string;
    endDate?: string | null;
    website?: string | null;
    showMockup: boolean;
    images?: Array<CreateProjectImage>;
    tags: Array<string>;
    repositories?: Array<CreateProjectRepository>;
};

export type CreateProjectImage = {
    id?: string | null;
    image?: Blob | File | null;
    type: ImageType;
    order?: number | null;
};

export type CreateProjectRepository = {
    id?: string | null;
    title: string;
    url: string;
    order?: number | null;
};

export type CreateTag = {
    title: string;
    type: TagType;
    icon?: string | null;
    customColour?: string | null;
};

export enum ImageType {
    LOGO = 'Logo',
    BANNER = 'Banner',
    CARD = 'Card',
    DESKTOP = 'Desktop',
    MOBILE = 'Mobile'
}

export type Project = {
    id: string;
    title: string;
    shortDescription: string;
    description: string;
    companyId?: string | null;
    company?: Company;
    startDate: string;
    endDate?: string | null;
    website?: string | null;
    showMockup: boolean;
    slug: string;
    images: Array<ProjectImage>;
    repositories: Array<ProjectRepository>;
    tags: Array<Tag>;
    relatedProjects?: Array<Project>;
    logo?: ProjectImage;
    readonly logoUrl?: string | null;
    card?: ProjectImage;
    readonly cardUrl?: string | null;
    banner?: ProjectImage;
    readonly bannerUrl?: string | null;
};

export type ProjectDescriptionSuggestionResponse = {
    projectId?: string;
    title?: string;
    existingDescription?: string;
    suggestedDescription?: string;
};

export type ProjectImage = {
    id: string;
    image: string;
    type: ImageType;
    order?: number | null;
    isOptimised?: boolean;
    projectId?: string;
};

export type ProjectRepository = {
    id: string;
    title: string;
    url: string;
    order?: number | null;
    projectId?: string;
};

export type SuggestProjectDescriptionRequest = {
    additionalContext?: string | null;
    additionalData?: {
        [key: string]: string;
    } | null;
    targetWordCount?: number | null;
};

export type Tag = {
    id: string;
    title: string;
    type: TagType;
    icon?: string | null;
    customColour?: string | null;
    slug: string;
};

export enum TagType {
    DEFAULT = 'Default',
    BACKEND = 'Backend',
    FRONTEND = 'Frontend',
    DEV_OPS = 'DevOps',
    OTHER = 'Other',
    DATA = 'Data',
    CMS = 'CMS',
    MOBILE = 'Mobile',
    AI = 'AI'
}

export type VertexCitation = {
    id?: string | null;
    featureType?: VertexFeatureType;
    title?: string | null;
    project?: Project;
    company?: Company;
    tag?: Tag;
};

export enum VertexFeatureType {
    PROJECT = 'Project',
    COMPANY = 'Company',
    TAG = 'Tag'
}

export type VertexQueryRequest = {
    query?: string;
};

export type VertexQueryResult = {
    answer?: string;
    citations?: Array<VertexCitation>;
};

export type ProjectWritable = {
    id: string;
    title: string;
    shortDescription: string;
    description: string;
    companyId?: string | null;
    company?: Company;
    startDate: string;
    endDate?: string | null;
    website?: string | null;
    showMockup: boolean;
    slug: string;
    images: Array<ProjectImage>;
    repositories: Array<ProjectRepository>;
    tags: Array<Tag>;
    relatedProjects?: Array<ProjectWritable>;
    logo?: ProjectImage;
    card?: ProjectImage;
    banner?: ProjectImage;
};

export type VertexCitationWritable = {
    id?: string | null;
    featureType?: VertexFeatureType;
    title?: string | null;
    project?: ProjectWritable;
    company?: Company;
    tag?: Tag;
};

export type VertexQueryResultWritable = {
    answer?: string;
    citations?: Array<VertexCitationWritable>;
};

export type GetCompanyData = {
    body?: never;
    path?: never;
    query?: {
        search?: string;
    };
    url: '/company';
};

export type GetCompanyResponses = {
    /**
     * OK
     */
    200: Array<Company>;
};

export type GetCompanyResponse = GetCompanyResponses[keyof GetCompanyResponses];

export type PostCompanyData = {
    body?: {
        createCompany?: CreateCompany;
    };
    path?: never;
    query?: never;
    url: '/company';
};

export type PostCompanyResponses = {
    /**
     * OK
     */
    200: Company;
};

export type PostCompanyResponse = PostCompanyResponses[keyof PostCompanyResponses];

export type DeleteCompanyByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/company/{id}';
};

export type DeleteCompanyByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetCompanyByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/company/{id}';
};

export type GetCompanyByIdResponses = {
    /**
     * OK
     */
    200: Company;
};

export type GetCompanyByIdResponse = GetCompanyByIdResponses[keyof GetCompanyByIdResponses];

export type PutCompanyByIdData = {
    body?: {
        createCompany?: CreateCompany;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/company/{id}';
};

export type PutCompanyByIdResponses = {
    /**
     * OK
     */
    200: Company;
};

export type PutCompanyByIdResponse = PutCompanyByIdResponses[keyof PutCompanyByIdResponses];

export type GetCompanyBySlugData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/company/{slug}';
};

export type GetCompanyBySlugResponses = {
    /**
     * OK
     */
    200: Company;
};

export type GetCompanyBySlugResponse = GetCompanyBySlugResponses[keyof GetCompanyBySlugResponses];

export type GetMediaUploadsByFileNameData = {
    body?: never;
    path: {
        fileName: string;
    };
    query?: never;
    url: '/media/uploads/{fileName}';
};

export type GetMediaUploadsByFileNameResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetProjectData = {
    body?: never;
    path?: never;
    query?: {
        search?: string;
    };
    url: '/project';
};

export type GetProjectResponses = {
    /**
     * OK
     */
    200: Array<Project>;
};

export type GetProjectResponse = GetProjectResponses[keyof GetProjectResponses];

export type PostProjectData = {
    body?: {
        createProject?: CreateProject;
    };
    path?: never;
    query?: never;
    url: '/project';
};

export type PostProjectResponses = {
    /**
     * OK
     */
    200: Project;
};

export type PostProjectResponse = PostProjectResponses[keyof PostProjectResponses];

export type DeleteProjectByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/project/{id}';
};

export type DeleteProjectByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetProjectByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/project/{id}';
};

export type GetProjectByIdResponses = {
    /**
     * OK
     */
    200: Project;
};

export type GetProjectByIdResponse = GetProjectByIdResponses[keyof GetProjectByIdResponses];

export type PutProjectByIdData = {
    body?: {
        createProject?: CreateProject;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/project/{id}';
};

export type PutProjectByIdResponses = {
    /**
     * OK
     */
    200: Project;
};

export type PutProjectByIdResponse = PutProjectByIdResponses[keyof PutProjectByIdResponses];

export type GetProjectBySlugData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/project/{slug}';
};

export type GetProjectBySlugResponses = {
    /**
     * OK
     */
    200: Project;
};

export type GetProjectBySlugResponse = GetProjectBySlugResponses[keyof GetProjectBySlugResponses];

export type GetProjectByIdRelatedData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/project/{id}/related';
};

export type GetProjectByIdRelatedResponses = {
    /**
     * OK
     */
    200: Array<Project>;
};

export type GetProjectByIdRelatedResponse = GetProjectByIdRelatedResponses[keyof GetProjectByIdRelatedResponses];

export type PutProjectimageOptimiseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/projectimage/optimise';
};

export type PutProjectimageOptimiseResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetTagData = {
    body?: never;
    path?: never;
    query?: {
        search?: string;
    };
    url: '/tag';
};

export type GetTagResponses = {
    /**
     * OK
     */
    200: Array<Tag>;
};

export type GetTagResponse = GetTagResponses[keyof GetTagResponses];

export type PostTagData = {
    body?: CreateTag;
    path?: never;
    query?: never;
    url: '/tag';
};

export type PostTagResponses = {
    /**
     * OK
     */
    200: Tag;
};

export type PostTagResponse = PostTagResponses[keyof PostTagResponses];

export type DeleteTagByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/tag/{id}';
};

export type DeleteTagByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetTagByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/tag/{id}';
};

export type GetTagByIdResponses = {
    /**
     * OK
     */
    200: Tag;
};

export type GetTagByIdResponse = GetTagByIdResponses[keyof GetTagByIdResponses];

export type PutTagByIdData = {
    body?: CreateTag;
    path: {
        id: string;
    };
    query?: never;
    url: '/tag/{id}';
};

export type PutTagByIdResponses = {
    /**
     * OK
     */
    200: Tag;
};

export type PutTagByIdResponse = PutTagByIdResponses[keyof PutTagByIdResponses];

export type GetTagBySlugData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/tag/{slug}';
};

export type GetTagBySlugResponses = {
    /**
     * OK
     */
    200: Tag;
};

export type GetTagBySlugResponse = GetTagBySlugResponses[keyof GetTagBySlugResponses];

export type PostVertexIngestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/vertex/ingest';
};

export type PostVertexIngestResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostVertexQueryData = {
    body?: VertexQueryRequest;
    path?: never;
    query?: never;
    url: '/vertex/query';
};

export type PostVertexQueryResponses = {
    /**
     * OK
     */
    200: VertexQueryResult;
};

export type PostVertexQueryResponse = PostVertexQueryResponses[keyof PostVertexQueryResponses];

export type PostVertexProjectsByIdDescriptionSuggestData = {
    body?: SuggestProjectDescriptionRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/vertex/projects/{id}/description/suggest';
};

export type PostVertexProjectsByIdDescriptionSuggestResponses = {
    /**
     * OK
     */
    200: ProjectDescriptionSuggestionResponse;
};

export type PostVertexProjectsByIdDescriptionSuggestResponse = PostVertexProjectsByIdDescriptionSuggestResponses[keyof PostVertexProjectsByIdDescriptionSuggestResponses];
