name: yarn build
on: [push]
jobs:
  build:
    name: yarn build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '21.6.0'
          cache: 'yarn' # cache dependencies
      - uses: borales/actions-yarn@v5.0.0
        with:
          cmd: install # will run yarn install command
      - uses: borales/actions-yarn@v5.0.0
        with:
          cmd: build # will run yarn build command
